[book]
authors = ["Mamba2410"]
language = "en"
multilingual = false
src = "src"
title = "Pokewalker Wiki"

[build]
build-dir = "../pokewalker-wiki-html"

[output.html]
site-url = "/pokewalker-wiki/"
additional-css = ["fixup.css"]

